-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE ebs_investigation (
    uuid text,
    form text,
    reported_by text,
    reported_by_parent text,
    signal_id text,
    signal_investigated text,
    cause text,
    signs_reported_fever text,
    signs_reported_cough text,
    signs_reported_breathing text,
    signs_reported_diarrhoea text,
    signs_reported_other text,
    signs_other text,
    travel_history text,
    contact_covid_case text,
    labs_sample text,
    num_people_exposed integer,
    num_suspected_cases integer,
    num_human_cases_hospitalized integer,
    num_human_deaths integer,
    event_risk_classification text,
    response_recommendations text,
    latitude text,
    longitude text,
    reported timestamp without time zone
);

