-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE ebs_verification (
    uuid text,
    form text,
    reported_by text,
    reported_by_parent text,
    signal_id text,
    signal_desc text,
    signal_confirmation text,
    signal_start_date text,
    num_people_symptoms text,
    num_people_dead text,
    additional_details text,
    signal_source text,
    source_specify text,
    threat_exists text,
    verification_date timestamp without time zone,
    latitude text,
    longitude text,
    reported timestamp without time zone
);

