-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE ebs_signal (
    uuid text,
    form text,
    reported_by text,
    reported_by_parent text,
    signal_id text,
    signal_code text,
    reported timestamp without time zone
);

