-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE VIEW ebsview_signal_verification AS  SELECT ebs_verification.uuid,
    ebs_verification.form,
    ebs_verification.reported_by,
    ebs_verification.reported_by_parent,
    ebs_verification.signal_id,
    ebs_verification.signal_desc,
    ebs_verification.signal_confirmation,
    ebs_verification.signal_start_date,
    ebs_verification.num_people_symptoms,
    ebs_verification.num_people_dead,
    ebs_verification.additional_details,
    ebs_verification.signal_source,
    ebs_verification.source_specify,
    ebs_verification.threat_exists,
    ebs_verification.verification_date,
    ebs_verification.latitude,
    ebs_verification.longitude,
    ebs_verification.reported
   FROM ebs_verification;

