-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE VIEW ebsview_signal_report AS  SELECT ebs_signal.uuid,
    ebs_signal.form,
    ebs_signal.reported_by,
    ebs_signal.reported_by_parent,
    ebs_signal.signal_id,
    ebs_signal.signal_code,
    ebs_signal.reported::timestamp with time zone AS reported
   FROM ebs_signal;

