-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE VIEW ebsview_signal_investigation AS  SELECT ebs_investigation.uuid,
    ebs_investigation.form,
    ebs_investigation.reported_by,
    ebs_investigation.reported_by_parent,
    ebs_investigation.signal_id,
    ebs_investigation.signal_investigated,
    ebs_investigation.cause,
    ebs_investigation.signs_reported_fever,
    ebs_investigation.signs_reported_cough,
    ebs_investigation.signs_reported_breathing,
    ebs_investigation.signs_reported_diarrhoea,
    ebs_investigation.signs_reported_other,
    ebs_investigation.signs_other,
    ebs_investigation.travel_history,
    ebs_investigation.contact_covid_case,
    ebs_investigation.labs_sample,
    ebs_investigation.num_people_exposed,
    ebs_investigation.num_suspected_cases,
    ebs_investigation.num_human_cases_hospitalized,
    ebs_investigation.num_human_deaths,
    ebs_investigation.event_risk_classification,
    ebs_investigation.response_recommendations,
    ebs_investigation.latitude,
    ebs_investigation.longitude,
    ebs_investigation.reported
   FROM ebs_investigation;

